### PR TITLE
Fix integration with scripted loadable module widget base class

### PR DESCRIPTION
**Pull request by jcfr**

### CODE REVIEW

**Comment by kirbyju** [comment]
I believe all of your changes have been applied, but I'm still not seeing the icon on my end.  Is it working for you now?

**Comment by jcfr** [comment]
When running from the build tree, the icon is indeed showing up expected:

image

**Comment by kirbyju** [comment]
Hmm, okay, well that's good.  Any idea why it's not showing up in my 5.6 install if I've merged all your changes to main and updated the 5.6 branch with those changes?  When I go to Extension Manager in v5.6 it's still showing the latest version of the extension is from 2023-11-26.  

image

**Comment by jcfr** [comment]
Following the release of `v5.6.1`, extensions are being built for that version and not for `v5.6.0` anymore.

You should see a notification in the welcome module suggesting you to update.

**Comment by kirbyju** [comment]
Hurray, it's working!  Thanks!

**Pull request merged**
